### ISSUE TITLE
Missing old API functions/events

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#1]
This new API seems much cleaner than the old JS API and using promises instead of the `OnAsyncCallback` system makes a lot of sense. I was really hoping that the new API would enable new functionality, though, but you seem to have actually *removed* some of the events and functions I was using. Specifically, there doesn't seem to be an `OnSceneLoad` event anymore and I don't see anything  that would be the equivalent of the `recstat` property in the old API. 

Using `recstat` to get the data about length, name, target file, etc of the currently active stream(s) is particularly important for several of the plugins I have built using the old system. I have one that tracks and saves scene changes to a file so that the video can be post-processed and one that displays a timer for the length of the current stream (so the people on camera know when to wrap up). 

Is there a way that I am missing to get this information with the new API? If not, is this something that is going to be added to the API soon?

**Comment by miyb** [comment]
We're glad to hear that the API feels cleaner. We had to redo the API as we learned a lot of lessons from the old one.

That said, there *are* a good number of things that are removed from the current release, either due to us not having implemented it yet, or an intentional removal of some things which we realized were buggy or cannot currently be implemented correctly without some additional changes to the underlying application. 

With regards to events and `recstat`, these are unfortunately not currently available with the new API but these are definitely in the pipeline (we did not remove these because of infeasibility concerns.) We will be exposing more functionality for sources and extensions soon.

**Comment by Matrim-Cauthon** [comment]
Hi, the latest release (0.7.0) should address the above (and issue #4 as well).

Events will be propagated to the corresponding window utility (`SourcePluginWindow`, `SourceConfigurationWindow`, `ExtensionWindow`). The [API docs](http://xjsframework.github.io/api.html#/window) document the current set of events. More will be implemented in the future. For your specific concern, extensions will now be able to handle the `scene-load` event. 

The `Channel` class (Core/Channel) handles the channel statistics. If more functionality is needed, feel free to submit an issue (or send a pull request :) ).

As for #4, a new set of methods for `HTMLItem` is now available.

Thanks for your feedback.

**Comment by paul-lrr** [comment]
Thanks for the additions! I'm excited with how fast this new plugin system is being improved on!
