### ISSUE TITLE
setItemOrder() breaking camera items and reloading items

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#106]
When I use `Scene.setItemOrder()` with an array of IDs, the order changes successfully, but any camera sources go black and have to be reconnected. It also seems to refresh all the items in the scene, for example things like timers reset and some items flicker as if they are loading. These issues don't happen when you reorder items in the source list, so I assume it is something specific with the `Scene.setItemOrder()` function.
It appears as if it is destroying all the items and then recreating them in the new order, instead of just moving them.

**Comment by dcefram** [comment]
I'll mark this as a bug.

The reason why this is happening is that if you use `setItemOrder` in an extension plugin, the framework will try to set the order by 'replacing' the presentation. Basically, it fetches all the items in the scene (ie. their xml representations), sorts them, and then replace the whole scene with the new XML preset.

This approach was supposed to be used if the you're trying to sort items in another scene, but the issue here is that it would only work if used [inside the source configuration window.](https://github.com/xjsframework/xjs/blob/master/src/core/scene.ts#L1216)

**Resolution:** Confirm if `SourcesListOrderSave` also works in extension environment. If yes, use that if called for the active scene. This would prevent the items from flickering and resetting.

**Limitation:** Setting the order of items of other scenes would still cause the items to reset (ie. if you have a js timer or something, it'll reset), since we can only use `SourcesListOrderSave` for the current scene. So we'll have to stick to 'replacing' the whole scene's contents with the 'cloned' contents that has the correct order.

**Comment by nelson-temporal** [comment]
Since the needed xbc changes were already implemented, we are now able to use SourcesListOrderSave inside extension window.

But still the limitation applies when trying to change the order of items from other scenes which would cause items to reset, since we can only use SourcesListOrderSave for the active scene.

**Comment by nelson-temporal** [comment]
Fixed resetting of sources when using setItemOrder and setSourceOrder on a non-active scene.
This was due to formatting inconsistencies on json object and final xml config.
