### ISSUE TITLE
Deleting Item from Extension

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#107]
The `System` module classes allow you to add an item to the current scene, but how do you remove an item? I don't see anything in the API documentation under Core.Scene, Core.Item or System. Am I missing something?

Some accidental experimentation with `Scene.setItemOrder()`  indicates that if you `setItemOrder` on a scene and omit an item id from the sorting array, that item is deleted as the items are reordered, but that doesn't seem very efficient. (this also relates to #106 with `setItemOrder` appearing to remove and then recreate each item in the new order)

**Comment by dcefram** [comment]
Seems like this is already available in XSplit Broadcaster... We'll have to add this to the framework :)

@Matrim-Cauthon @SML-MeSo @virn: Any info about 1.5.0? We could probably add this feature-request since it's straightforward to implement. Should be available for both the `Core.Item` class and the `Core.Scene` class.

**Comment by Matrim-Cauthon** [comment]
Yep this seems like a very essential feature, and it's easy to implement, so let's add this to the next release.

For maximum flexibility we can make use of `Item.remove(id)`, or `Item#remove()` to remove a specific instance of a video item. With global sources in play, perhaps we also implement `remove` at the `Source` level to remove all items in its item list?
