### ISSUE TITLE
Dialog result not being returned by a spawned new dialog

### ISSUE THREAD

**Issue by SML-MeSo** [xjsframework/xjs#115]
This issue is encountered in the current internal builds for XBC. This is due to the CEF update which now uses Chrome 52 (of which Object.observe is removed). Proposed resolution is to switch implementation to using proxies instead.

**Comment by dcefram** [comment]
All looks well... though I think we can just make it a habit not to use `var`... use `let` instead if we're going to modify the variable, else, use `const`.

https://github.com/xjsframework/xjs/commit/9a7edb03f47413a4642733b41d89495814d346f7#diff-961e415905a925e60847a1e0066ec781R10

Ref: http://programmers.stackexchange.com/a/274352

**Comment by dcefram** [comment]
I just realized that this would break the plugins that uses dialog.ts in the current latest public version of XSplit Broadcaster :((

We should add some version checkers on dialog.ts (use Proxy if version 2.9+, else, use Object.observe). And since you just got married and is in a honeymoon period, I'll do the fixes <3

**Comment by dcefram** [comment]
Assigning to @SML-MeSo for review before pushing to release branch
