### ISSUE TITLE
Plugin does not save configuration after swapping with item in preview editor

### ISSUE THREAD

**Issue by dcefram** [xjsframework/xjs#118]
If a plugin with global source enabled is swapped with the same source through the preview editor, the plugin will not be able to update its own configuration. There are no recovery procedure after this bug has occurred.

**Comment by Matrim-Cauthon** [comment]
Let's fix this bug for the framework, but let's add a "best practice" description in our documentation (possibly add it to "Common Errors" tutorial for now?) that states that developers should ideally do Source/Item operations on load, and if that's not possible, always get an updated set of object references because IDs are not guaranteed to be stable especially with the preview editor involved.

**Comment by virn** [comment]
I've been trying to replicate the issue on other Source Plugins, but could only do it with **Youtube Live Chat Viewer - Beta**. @dcefram can you confirm this?
Other than adding the Plugin again to use it, toggling global source on and off works to reset the config window with the settings preserved.

**Comment by dcefram** [comment]
Yes, Youtube Live Chat Viewer only has that issue since all other plugins uses XJS Framework version lower than 1.4.0 (Version 1.4.0 included some logic for handling the global source, which is the main culprit of this issue)
