### ISSUE TITLE
Better handling of videoitems linked to the same source

### ISSUE THREAD

**Issue by Matrim-Cauthon** [xjsframework/xjs#119]
Since XSplit is modifying the concept of global sources to be more intuitive, we need to modify the framework to reflect these changes.

Framework level changes:
1) The `prop:globalsrc` property is now totally separate from "Keep Loaded in Memory". To preserve behavior with XBC 2.8, make sure that we only separate setting/checking of both props in XBC 2.9, onwards.
2) XBC 2.9 now allows improved functionality, so we will need to modify `Item.duplicate` to allow to duplicate/paste as linked or unlinked to the original source.
3) `name` and `cname` are now the same across all linked items. Make sure that these are shown to be common to all of the renderers for a specific source. (Documentation wise: please add comments to those methods saying that in XBC 2.8, names may be different but in 2.9, they are the same across all items linked to the same source.)

Documentation changes:
Simply reduce the mention of "global" and use "linked" more often. Let's also make the doc for this more complete (give examples for the actual XBC 2.9 behavior, then give code examples to accomplish the same).

**Comment by virn** [comment]
Here are the changes I made for each item:
1. Added globalsrcMinVersion(2.9) on util/version to use as checking for the application of prop:globalsrc on setKeepLoaded and no longer set it if the current version is greater.

2. Item.duplicate now accepts a parameter(boolean) to set if the duplicate item would be linked or not to the original item. Not adding a parameter would default it to unlinked. Additionally, per reading the discussion on **XBC-5883**, I added a condition to set "keeploaded" to true if parameter is set to **true**.

3. Updated the docs for name and cname to specify the changes made in 2.9 and the behavior it used to have on 2.8. And latest docs use link/linked instead of global.

Additional:
1. I also created a Item.unlink method following **XBC-5883**.
- Unlink methods sets "prop:globalsrc" to 0 of the item. Would unlink selected Item to the other Items that may be linked to a source.

2. There's also a test method Item.duplicateToScene that duplicates an item to a specified scene.

**Comment by Matrim-Cauthon** [comment]
Following comments are for #111 and #119 combined. This might not be an exhaustive list so we will need to go through another round of review later.

- `Item.duplicate` currently is written to be a breaking change with respect to the previous `xjs` version.
a. `options` object should be optional
b. `linked` and `scene` should be optional
c. default behavior should be unlinked

- `Item.duplicate` should be unlinked by default, to maintain compatibility with `xjs@1.4.0` behavior.
- `Item.duplicate` should only accept a `Scene` instead of generic `Object` for the `scene` option
- `Logger` already contains logic to determine if a warning should be called exactly once. Don't reimplement in every single method call. (If `Logger` logic is broken, fix it there.)
- Warning text should be more useful. "Use this through Source to avoid this warning" does not really inform / educate the developer.
- Keep loaded logic is broken for XBC 2.8 (`prop:globalsrc` is always set to 0)
- Review which methods require source vs. item warnings. For example, `getSourceId` does not really need a warning because both `Item` and `Source` instances should have a corresponding source ID anyway.
- `Item` should implement `iSource`
- For more concise documentation (and to clearly show that certain properties are source-level), doc-comments for source properties which are duplicated in item should simply link to the source's docs. For example, in 2.9, name and custom name are source-level. In `Item`, their docs should simply be a one-line link to `Source.setName` (similar to how `Item.setPosition` simply links to `IItemLayout.setPosition`.
- Do not leak implementation details in comments. For example, in `Item.unlink()`, do not mention that it is setting `globalsrc` to 0. Implementation details can change anytime.

**Comment by virn** [comment]
Item finished and closed on 7bf0409
