### ISSUE TITLE
Allow browser sources to render up to 60 fps

### ISSUE THREAD

**Issue by SML-MeSo** [xjsframework/xjs#129]
Right now, HTML sources can only render up to a maximum of 30 fps. We need a setting to enable it to render at a maximum of 60 fps.

**Comment by SML-MeSo** [comment]
Accomplishment of this issue also entails removing the '60 FPS Browser Sources' section in the tutorials of the XJS framework website. It also needs to have a note that feature is still experimental, either through the API or an info once used.

**Comment by Matrim-Cauthon** [comment]
@SML-MeSo please don't delete the tutorial; just modify it to show the xjs methods instead of raw Broadcaster API methods. It is still a very helpful resource to developers taking a look at what can be done with XSplit.

Also, if I recall correctly, XSplit (not sure where exactly) has a link to the 60 FPS post.

**Comment by SML-MeSo** [comment]
comment updated :D
