### ISSUE TITLE
Scene thumbnail and scene/source textures

### ISSUE THREAD

**Issue by mikeybanez** [xjsframework/xjs#136]
Let's consider how we can expose these features to allow drawing of previews onto extensions.
1.) method to acquire a base64 PNG thumbnail of a scene
2.) methods to render a scene or a source/videoitem onto a WebGL texture

**Comment by virn** [comment]
1. Would be  easy to implement since all the calls needed is already available. The Scene method would return something like `data:image/png;base64, url`. 
2. For this I'd like to have some inputs as to what the method should require.
    - image from #1
    - canvas element
    - scale? size? (for quality)
    - ??
or should this method work independently from #1 and require a scene/scene number instead of image and work from there.

**Comment by Matrim-Cauthon** [comment]
Yes, 1 should be straightforward. 2 shouldn't need the image from 1 because this is a totally different technique being done in the core.

If we look at our WebGL experiments, all that the `dupworkspace` call needs is the raw shared handle of the WebGL texture and the target scene, but we can consider auxiliary requirements (e.g., There should be a canvas, There should be a texture with the SHARED flag enabled) as candidates for new API calls, so that developers don't need to set up the entire system themselves.

At the moment I imagine the following API (the names are not final at all)
- `TellXBCToDrawToTexture(textureId, sceneIndex)` - serves as the basic method call for the feature
- `ToggleTextureRendering(state?)` - basically a start/stop for rendering
- `PrepareCanvasForRendering(canvas, fps?)` - prepares a target canvas. Its only job is to render the texture on the entire size of the canvas.

Please review the WebGL demos and see if you can give another proposal for the shape of our API. Note that the above does not yet even consider the case of transferring data to a remote page. Because of the complexity of this API, it might make sense to separate this into another module instead of putting this in `Scene`.

**Comment by virn** [comment]
Additional requirement for this has been filed on XBC-6634.

**Comment by virn** [comment]
Development for this item can now proceed with the completion of XBC-6634.

**Comment by virn** [comment]
Moving this item to 2.7.0, since the Thumbnail class is now ready for testing and methods to render scene/videoItem/source will be handled in #189.
