### ISSUE TITLE
Erroneous values when dealing with multiple videoitem's properties

### ISSUE THREAD

**Issue by mikeybanez** [xjsframework/xjs#153]
Consider a scene with at least 3 _different_ game sources, and give them at least 3 _different_ custom names. Now, when I want to get a list of item ids + names + cnames, I can try the following code:

```
let items, ids, cnames, names;
Scene.getById(Number(sceneIndex) + 1)
  .then(scene => {
    return scene.getItems();
  })
  .then(itemList => {
    items = itemList;
    return Promise.all(items.map(item => item.getId()));
  })
  .then(idList => {
    ids = idList;
    return Promise.all(items.map(item => item.getCustomName())
  })
  .then(cnameList => {
    cnames = cnameList;
    return Promise.all(items.map(item => item.getName()));
  })
  .then(nameList => {
    names = nameList;
    let enumerated = ids.map((id, index) => {
      return {
        name: cnames[index] !== '' ? cnames[index] : names[index],
        id
      };
    });
    console.log(enumerated);
  });
```

Unfortunately, I seem to be getting incorrect names as a result. https://321.show/HlFN8HDm0TX You will notice that some item properties seem to have been acquired from other items.

I tried rewriting the source code to the following: 
```
Scene.getById(Number(sceneIndex) + 1)
  .then(scene => {
    return scene.getItems();
  })
  .then(itemList => {
    return Promise.all(itemList.map(item => {
      return Promise.all([
        item.getId(),
        item.getCustomName(),
        item.getName()
      ])
    }));
  })
  .then(itemDetailsArray => {
    let enumerated = itemDetailsArray.map(details => {
      return {
        id: details[0],
        name: details[1] !== '' ? details[1] : details[2]
      }
    });
    console.log(enumerated);
 });
```

Unfortunately, this still gives the same result.

**Comment by Matrim-Cauthon** [comment]
@SML-MeSo perhaps you can also provide some minimal source code to show the issues you encountered when dealing with multiple videoitem properties.

**Comment by virn** [comment]
Initial check on the issue brought me to internal item method(**get**) that handles an Item's local property and the **wrapget** method that contains checking for instances when an **Item** may no longer be on a certain scene but an instance of it is could still be on a different one, by checking the **Source**.

Made test using **wrapget** instead of the usual direct **get** call and was able to produce the desired result for given sample codes.

I will check this on further and dissect **wrapget** to know what could be missing on the steps of **get** method that makes it behave this way.
