### ISSUE TITLE
Create version bumping task

### ISSUE THREAD

**Issue by Matrim-Cauthon** [xjsframework/xjs#16]
For a quicker release process. This should update both npm and bower version numbers.

If possible, we should also automatically add the version number as a comment in the build.

**Comment by dcefram** [comment]
@Matrim-Cauthon, should we go ahead and use `npm version minor`? I found this on NPM website:

>Although npm can be used programmatically, its API is meant for use by the CLI only, and no guarantees are made regarding its fitness for any other purpose. If you want to use npm to reliably perform some task, the safest thing to do is to invoke the desired npm command with appropriate arguments.

We could however go ahead and use it programmatically, but there are alternatives to this.

- One is by updating the package.json and bower.json files
- Or, by executing a CLI command through nodejs using `require('child_process').exec`

**Comment by Matrim-Cauthon** [comment]
> should we go ahead and use npm version minor

Note that we don't just need to bump the minor version. This will be true especially when we do *true* semver, which will happen when we get to a stable version --- 1.X.X or higher.

I'm biased towards a gulp-based approach since we're using that to define our most-commonly used tasks anyway. How it's implemented under the hood is not important as long as we're able to specify how to bump the version number :+1:

**Comment by dcefram** [comment]
The npm version minor was just an example. So we'll just go ahead and do this:
> One is by updating the package.json and bower.json files

This way, we will be the ones to manually commit the changes, and manually add the tag. I believe this is OK since we usually bump the versions on the develop or release branch, while we tag the versions on our master branch.

The command would be like this:
```
gulp version --major|minor|patch --up|down
```

Without the flags, it would behave as `gulp version --minor --up`

What this gulp task would do is execute the `default` task first, then execute the version up/down task.
