### ISSUE TITLE
Writing to the disk

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#7]
Javascript security restriction make sense on the web, but XSplit is a very different environment than using it on a public website. The `io class` has methods for reading files from the disk and from a URL, but what is really needed is a method to *write* files to the hard drive (even if it is restricted to a special "XSplit files" folder). It would also be helpful to be able to get the attributes of a file (modification date, size, etc) without getting the contents so that a file could be easily monitored for changes and to get a list of the files (and folders) in a directory.

Being able to write files to the computer and monitor files for changes would enable 2 way data transfer between a plugin/extension and command line tools, custom GUI apps and other programs on the computer.

**Comment by dcefram** [comment]
Yeah, we see the possibilities of such functionality, which is now possible with the latest XSplit Broadcaster client. We will implement 'unsafe' methods on the framework (methods that would prompt the users if they would allow the plugin some rights) possibly on the next version :)

We generally consider methods that could write/manipulate data on the user's disk as unsafe due to obvious reasons (ie. someone could write malicious code to write some data to the users disk)

**Comment by tkntobfrk** [comment]
I've been considering creating a wrapper for this exact scenario in nodejs as an easy workaround. I run a nodejs program as part of my solution, which writes and interacts with the local file system & AWS  resources, twitter, etc.

I spun up an example about a month ago based on stream control http://www.farpnut.net/streamcontrol qt based app.

https://github.com/tkntobfrk/streamControl

Plugin script plugin in xsplit, which then interacts with nodejs, which in turn does whatever you need locally and/or externally. 

My usage doesn't exactly map the above as I drive changes to node through a queue, from a plugin page but would work either way as far as I can tell.

**Comment by dcefram** [comment]
Yes, you could do it that way. You could always create a nodejs software (or any language wherein you could create a software that could communicate through probably websockets, since it is readily available with plain javascript). Have a software that could receive data through websockets, then save the data retrieved to your disk.

This would work, but it'll be neater if our framework could do that out of the box with a simple method, which we would actually do add that up on possibly the next version, since it is already supported by our latest XSplit Broadcaster software :)

**Comment by paul-lrr** [comment]
In a similar vein, my current workaround is sending file writes through a little php script running on a local dev server, but obviously doing it without external dependencies would be much cleaner.

**Comment by Matrim-Cauthon** [comment]
We're moving support for file writing into the next milestone. We're planning to have DLLs to allow this functionality but we would like to have some minimum level of security on the application-level first before we release this.

Of course we can't really stop developer creativity from finding workarounds as described above :grinning: but when we release DLL support we'd like to encourage usage of *that*, as our current plans involve notifications for users when their plugin wants to access possibly unsafe methods.

**Comment by dcefram** [comment]
This feature is now supported using the DLL class. For more information on how to use the DLL class to actually write to disk, please check out our tutorial: http://xjsframework.github.io/tutorials.html#/dll
