### ISSUE TITLE
Most efficient way of show/hide item

### ISSUE THREAD

**Issue by tkntobfrk** [xjsframework/xjs#9]
I played around with .setVisible(false), and noticed some newer methods like searchAllForItemId & getCustomName. What do you think the best way to show/hide an individual item would be in the new framework?

I was considering exploring searchAllForItemId.

It seems like a function could be created, takes in Custom Name as search parameter + true/false

That function could get the ID and pass it to a function with searchAllForItemId, which you could then chain the visible true/false state to? 

But perhaps there's some incompleteness or speed impacts of doing it that way. Just wondering what would be the best way in the current framework.

**Comment by dcefram** [comment]
We have a method under Scene class called `searchAllForItemName`, which I think is roughly similar to the function that you wanted to create, just that instead of searching by custom name, it would search by the actual name (prop:name).

I guess we could consider adding a method like `searchAllForItemCName` (or something along that line) or add a parameter on `searchAllForItemName` for searching by custom name rather than the actual name. (mentioning @Matrim-Cauthon  and @SML-MeSo for your thoughts on this one if you guys think it's worth implementing)

There's a speed impact on using these methods since it basically iterates through all Scenes and would fetch all items within each scene, and then fetch the name using `getName` method. So the 'speed' of the method would most likely depend on how many items are placed on your scenes.

Also, please do note that we do not currently have any Flash Item object/class. What these translate to is that flash items would implement the base `Item` class, which does not have the `setVisible` method. We noticed that feature missing after releasing 0.7.0 version. But don't worry, we'll be releasing the next version that would include the `FlashItem` subclass ;)

**Comment by hlevring** [comment]
>add a parameter onsearchAllForItemName for searching by custom name rather
than the actual name

Definitely needed to be able to find items by custom name. Perhaps you may
also just consider that if cname is there then it replaces name

**Comment by dcefram** [comment]
Makes sense, we'll include that on the next version :)
That enhancement/method update will be tracked on issue #10

**Comment by Matrim-Cauthon** [comment]
It appears that the question has been addressed now, so I'll be closing this item.

Changes/updates to the framework relevant to this question will be found at #10 (and possibly #22).
