### ISSUE TITLE
Getting or setting the saved recording filename

### ISSUE THREAD

**Issue by paul-lrr** [xjsframework/xjs#91]
When a channel that has "save to local drive" enabled is online, is there a way to get the name/path of the file that is being written? Or even better, is there a way to specify what this file should be called?
With the old API, the `recstat` property returned an xml  object that could be parsed for a bunch of information about the active streams including the name of the local recording file, but I can't see where that info is in the new system.

**Comment by dcefram** [comment]
Hi, the framework does not currently support that. But the getting of name/path of the file that is being written should be relatively easy to implement on the framework, under the Channels class, we'll have to just add it there. We'll work on this, hopefully we'll release it on the next framework version.

As for the setting of name/path, I believe we will need to pass this through XSplit's PM group since this feature is not yet support by XSplit itself (XSplit automatically sets the path and filename of the recorded files)

Tagging @SML-MeSo and @Matrim-Cauthon for your thoughts on this issue.

**Comment by paul-lrr** [comment]
One wrinkle to this is that Xsplit seems to have recently changed its behavior with regards to naming the local recordings. When you start a stream, the local recording is named with the starting date and time as it always has been, but now when you stop the stream, it _renames_ the file to the stream _ending_ date and time. I have no idea when/why this change was made as it seems to add a lot of complexity and makes it much more difficult to programmatically access that stream recording. 

Being able to manually specify the stream recording name would make things much easier, but failing that (and in reference to issue #5 ) if a potential stream stop event could also return the _new_ name of the local recording, that would be handy

**Comment by dcefram** [comment]
In that case, I guess #5 should do the job... We'll move its target milestone from 1.5.0 to 1.4.0. We'll probably release a developer build when we're done with 1.4.0 (which should have the stream start and stream end events ready)

The change made with how local recordings are named was introduced in XSplit Broadcaster 2.7, but the reason behind that is beyond my paygrade. With that said, I hope #5 would solve this issue.

**Comment by Matrim-Cauthon** [comment]
Internal XSplit item XBC-5171 now emits events when the recording filenames get changed. This should make it easier to track not just simple local recordings, but also local recordings set to split the output files at a specific file size or time interval.

Initially assigning this item to 1.5.0 :tada:
